config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dashboard.urls")),
    path("user", include("user.urls")),
]

dashboard/api/urls.py
from django.urls import include, path

urlpatterns = [
    path("v1/", include("dashboard.api.v1.urls")),
]

dashboard/api/v1/urls.py
from django.urls import include, path

from .router import router

urlpatterns = [path("", include(router.urls))]

dashboard/urls.py
from django.urls import include, path

from dashboard.views import (
    ShareCreateView,
    ShareDeleteView,
    ShareDetailView,
    ShareListView,
    ShareUpdateView,
)

app_name = "dashboard"

urlpatterns = [
    path("", ShareListView.as_view(), name="index"),
    path("<int:pk>", ShareDetailView.as_view(), name="detail"),
    path("create", ShareCreateView.as_view(), name="create"),
    path("update/<int:pk>", ShareUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", ShareDeleteView.as_view(), name="delete"),
    path("api/", include("dashboard.api.urls")),
]

user/urls.py
from django.urls import path

from user.views import AuthView, LogoutView, RegistrationView

app_name = "user"

urlpatterns = [
    path("login/", AuthView.as_view(), name="auth"),
    path("registration/", RegistrationView.as_view(), name="registration"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

dashboard/models.py
from django.db import models


class Share(models.Model):
    """Акция"""

    figi = models.CharField(max_length=255, unique=True)
    isin = models.CharField(max_length=255)
    name = models.CharField(max_length=255, verbose_name="Наименование компании")
    ticker = models.CharField(max_length=10, unique=True, verbose_name="Тикер")
    currency = models.CharField(max_length=20, verbose_name="Валюта")
    uid = models.CharField(max_length=255, unique=True)
    last_price = models.FloatField(blank=True, null=True, verbose_name="Текущая цена")
    is_trend_high = models.BooleanField(
        blank=True, null=True, verbose_name="Растет цена"
    )
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta:
        verbose_name = "Акция"
        verbose_name_plural = "Акции"

user/models.py
from django.contrib.auth import get_user_model

User = get_user_model()

dashboard/forms.py
from django import forms

from .models import Share


class ShareModelForm(forms.ModelForm):
    """Инструмент"""

    class Meta:
        model = Share
        fields = "__all__"

user/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError

from user.models import User


class RegistrationForm(forms.Form):
    """Форма регистрации пользователей"""

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={"class": "form-control my-3 p-4", "placeholder": "Email"}
        ),
    )
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "form-control my-3 p-4", "placeholder": "Пароль"}
        ),
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "form-control my-3 p-4", "placeholder": "Повторите пароль"}
        ),
    )

    def clean(self):
        super().clean()
        email = self.cleaned_data["email"]
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]
        if password1 and password2 and password1 != password2:
            errors = ["Введенные пароли не совпадают"]
            raise ValidationError(errors)

        user = User.objects.filter(email=email)

        if user:
            errors = [
                "Данный e-mail уже зарегистрирован! Введите другой e-mail или"
                " воспользуйтесь формой авторизации."
            ]
            raise ValidationError(errors)

    def save(self):
        email = self.cleaned_data["email"]
        password = self.cleaned_data["password1"]
        User.objects.create_user(email, email, password)
        user = authenticate(username=email, password=password)
        return user


class AuthForm(forms.Form):
    """Форма авторизации пользователей"""

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={"class": "form-control my-3 p-4", "placeholder": "Email"}
        ),
    )
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "form-control my-3 p-4", "placeholder": "Пароль"}
        ),
    )

dashboard/api/v1/views.py
from django_filters import rest_framework as filters
from rest_framework import viewsets
from rest_framework.filters import OrderingFilter, SearchFilter

from dashboard.models import Share

from .serializer import ShareSerializer


class ShareFilter(filters.FilterSet):
    class Meta:
        model = Share
        fields = ("name", "ticker")


class ShareViewSet(viewsets.ModelViewSet):
    serializer_class = ShareSerializer
    queryset = Share.objects.all()
    filter_backends = (OrderingFilter, filters.DjangoFilterBackend, SearchFilter)
    filterset_class = ShareFilter
    ordering_fields = ["name", "ticker"]
    search_fields = ["$name"]

dashboard/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, View, UpdateView

from .forms import ShareModelForm
from .models import Share
from .services.graph import get_graph
from django.contrib.auth.mixins import UserPassesTestMixin


class IsUserAuthenticatedMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_authenticated

    @staticmethod
    def handle_no_permission():
        return redirect("dashboard:index")


class ShareListView(ListView):
    """Список акций"""

    model = Share
    template_name = "dashboard/list.html"
    paginate_by = 100
    ordering = ["name"]


class ShareDetailView(View):
    @staticmethod
    def get(request, pk):
        share = Share.objects.get(id=pk)

        return render(
            request,
            "dashboard/detail.html",
            {"plot_div": get_graph(share), "share": share},
        )


class ShareCreateView(IsUserAuthenticatedMixin, CreateView):
    """Добавление инструмента"""

    template_name = "dashboard/create.html"
    form_class = ShareModelForm
    success_url = reverse_lazy("dashboard:index")


class ShareUpdateView(IsUserAuthenticatedMixin, UpdateView):
    """Редактирование инструмента"""

    model = Share
    template_name = "dashboard/create.html"
    form_class = ShareModelForm
    success_url = reverse_lazy("dashboard:index")


class ShareDeleteView(IsUserAuthenticatedMixin, DeleteView):
    """Удаление задачи"""

    model = Share
    template_name = "dashboard/delete.html"
    success_url = reverse_lazy("dashboard:index")

user/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.views.generic import View

from .forms import AuthForm, RegistrationForm


class AuthView(View):
    """Авторизация"""

    @staticmethod
    def get(request):
        return render(request, "user/auth.html", {"form": AuthForm})

    @staticmethod
    def post(request):
        form = AuthForm(request.POST)
        user = authenticate(
            request, username=form.data["email"].lower(), password=form.data["password"]
        )

        if user is not None:
            login(request, user)
            return redirect("dashboard:index")
        else:
            return render(
                request,
                "user/auth.html",
                {
                    "form": form,
                    "error": "Неверный логин или пароль! Повторите попытку.",
                },
            )


class RegistrationView(View):
    """Регистрация"""

    @staticmethod
    def get(request):
        return render(request, "user/registration.html", {"form": RegistrationForm})

    @staticmethod
    def post(request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("dashboard:index")
        else:
            return render(
                request,
                "user/registration.html",
                {"form": form, "error": form.errors["__all__"].data[0].message},
            )


class LogoutView(View):
    """Выход"""

    @staticmethod
    def get(request):
        logout(request)
        return redirect("dashboard:index")

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">

    {% block title %}
    {% endblock %}

    {% load static %}
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <link href="{% static 'dashboard/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'dashboard/css/sticky-footer-navbar.css'%}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>


</head>
<body class="d-flex flex-column h-100">

<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'dashboard:index' %}" class="nav-link px-2 link-secondary">Главная</a></li>
        </ul>

        <div class="col-md-3 text-end">
            {% if user.is_authenticated %}
                <p>Привет, {{ user.email }}
                <a href="{% url 'user:logout' %}" class="btn btn-primary">Выход</a>
                </p>
            {% else %}
                <a href="{% url 'user:auth' %}" class="btn btn-primary">Войти</a>
            {% endif %}

        </div>
    </header>
</div>

<main class="flex-shrink-0">
    <div class="container">

        {% block content %}
        {% endblock %}


    </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="{% url 'dashboard:index' %}" class="nav-link px-2 text-muted">Главная</a></li>
        </ul>
        <p class="text-center text-muted">Investing</p>
    </div>
</footer>


</body>
</html>

dashboard/templates/dashboard/create.html
{% extends "dashboard/base.html" %}

{% block title %}
<title>Добавить инструмент</title>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            {{ field|as_crispy_field }}
            {% endfor %}
            <button class="w-100 btn btn-lg btn-primary mt-5" type="submit">Сохранить</button>
        </form>
    </div>
    <div class="col-4"></div>
</div>
{% endblock %}

dashboard/templates/dashboard/delete.html
{% extends "dashboard/base.html" %}

{% block title %}
    <title>Удаление инструмента</title>
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить инструмент: <b>"{{ share.name }}"</b> ?</p>
        <input type="submit" class="btn btn-sm btn-outline-danger rounded-pill" value="Удалить" />
    </form>

{% endblock %}

dashboard/templates/dashboard/detail.html
{% extends "dashboard/base.html" %}

{% block title %}
<title>Детальная информация</title>
{% endblock %}

{% block content %}
    <div class="row">
    <div class="col3"></div>
    <div class="col3">
        Инструмент: {{ share.name }} <br>
        Текущая цена: {{ share.last_price }} {{ share.currency }} <br>
        Время последнего обновления: {{ share.updated_at }}
    </div>
    <div class="col3"></div>
    </div>


      <div class="row mt-3">
    <div class="col3"></div>
    <div class="col3">
    <h5>Исторические данные: </h5>
 {% autoescape off %}
  {{ plot_div }}
  {% endautoescape %}
    </div>
    <div class="col3"></div>
    </div>



{% endblock %}

dashboard/templates/dashboard/list.html
{% extends "dashboard/base.html" %}

{% block title %}
    <title>Список акций</title>
{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
        <div>
            <a href="{% url 'dashboard:create' %}" class="btn btn-primary">Добавить</a>
        </div>
    {% endif %}

    {% if share_list %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Тикер</th>
                <th scope="col">Название</th>
                <th scope="col">ISIN</th>
                <th scope="col">Текущая цена</th>
                {% if user.is_authenticated %}
                    <th scope="col">Управление</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>

            {% for share in share_list %}
                <tr>
                    <td><a href="{% url 'dashboard:detail' share.id %}"> {{share.ticker}} </a></td>
                    <td>{{share.name}}</td>
                    <td>{{share.isin}}</td>
                    {%  if  share.is_trend_high %}
                        <td style="background-color: mediumseagreen">
                            {%  else  %}
                        <td style="background-color: palevioletred">
                    {% endif %}
                    {{share.last_price}} {{ share.currency }}</td>
                    {% if user.is_authenticated %}
                        <td>
                            <a href="{% url 'dashboard:update' share.id %}" class="btn btn-secondary">
                                Редактировать
                            </a>
                            <a href="{% url 'dashboard:delete' share.id %}" class="btn btn-danger">
                                Удалить
                            </a>
                        </td>
                    {% endif %}

                </tr>
            {% endfor %}



            </tbody>
        </table>

        <div class="btn-group" role="group" aria-label="Item pagination">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
            {% endif %}

            {% for page_number in page_obj.paginator.page_range %}
                {% if page_obj.number == page_number %}
                    <button class="btn btn-outline-primary active">
                        <span>{{ page_number }} <span class="sr-only">(current)</span></span>
                    </button>
                {% else %}
                    <a href="?page={{ page_number }}" class="btn btn-outline-primary">
                        {{ page_number }}
                    </a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
            {% endif %}
        </div>


    {% else %}
        <p>Акций еще нет</p>
    {% endif %}


{% endblock %}

user/templates/user/auth.html
{% extends "user/base.html" %}
{% block content %}
<form  action="{% url 'user:auth'%}" method="POST">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Войдите в профиль</h1>

    <div>
        {{ form.email }}
    </div>
    <div>
        {{ form.password }}
    </div>
    <div>
        {{ error }}
    </div>

    <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
    <p class="text-center text-uppercase text-muted pt-3">--- Или ---</p>
    <a href="{% url 'user:registration' %}" class="w-100 btn btn-lg btn-outline-primary">Зарегистрироваться</a>
</form>
 {% endblock %}

user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Investing / Авторизация</title>

    {% load static %}
    <link href="{% static 'user/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'user/css/signin.css'%}" rel="stylesheet">

</head>
<body>

<main class="form-signin">

    {% block content %}
    {% endblock %}

</main>


</body>
</html>

user/templates/user/registration.html
{% extends "user/base.html" %}
{% block content %}
    <form  action="{% url 'user:registration'%}" method="POST">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Регистрация в системе</h1>

        <div>
            {{ form.email }}
        </div>
        <div>
            {{ form.password1 }}
        </div>
        <div>
            {{ form.password2 }}
        </div>
        <div>
            {{ error }}
        </div>

        <button class="w-100 btn btn-lg btn-primary" type="submit">Зарегистрироваться</button>
        <p class="text-center text-uppercase text-muted pt-3">--- Или ---</p>
        <a href="{% url 'user:auth' %}" class="w-100 btn btn-lg btn-outline-primary">Войти</a>
    </form>
{% endblock %}